name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Build
      run: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" NovasFuckery/NovasFuckery.csproj
